/border_checker:
  ros__parameters:
    filter_field: z
    filter_limits_max: -0.2
    filter_limits_min: -1.0
    filter_type: filter
    mean_k: 10
    output_topic: filter
    standard_dev_thresh: 0.1
    use_sim_time: false
